---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
      - id: debug-statements
        name: check for debug statements
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: check for hardcoded secrets
        exclude: docker-compose.*
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        name: check yaml
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.2
    hooks:
      - id: hadolint
        name: check Dockerfile
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
      - id: python-use-type-annotations
        name: check that python type annotations not comments
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: check python docstrings
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: check python style and quality
        # E501 black will handle most of the issues
        args: ["-j8", "--ignore=E501,W503"]
        exclude: (migrations)
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: format python
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: sort python imports
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-ll", "--skip=B608"]
        name: security audit for python
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.0
    hooks:
      - id: gitlint
        name: check commit message
