---
version: "3.9"

x-common: &common
  restart: unless-stopped

x-common-environment: &common-environment
  DB_HOST: ${DB_HOST?}
  DB_NAME: ${DB_NAME?}
  DB_PASSWORD: ${DB_PASSWORD?}
  DB_PORT: ${DB_PORT-5432}
  DB_USER: ${DB_USER?}
  SECRET_KEY: ${SECRET_KEY?}
  SUPERUSER_EMAIL: ${SUPERUSER_EMAIL?}
  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD?}
  SUPERUSER_USERNAME: ${SUPERUSER_USERNAME?}

services:
  traefik:
    <<: *common
    image: "traefik:${TRAEFIK_VERSION-2.6}"
    command:
      - --accesslog=true
      - --api.insecure=true
      - --entrypoints.http.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - backend

  backend:
    <<: *common
    build: backend
    environment:
      <<: *common-environment
      LOG_FILE: /app/logs/backend.log
    labels:
      traefik.enable: true
      traefik.http.middlewares.backend_compress.compress: true
      traefik.http.routers.backend.entrypoints: http
      traefik.http.routers.backend.rule: PathPrefix(`/`)
      traefik.http.routers.backend.middlewares: backend_compress
      traefik.http.services.backend.loadbalancer.server.port: 80

volumes:
  logs: {}
